### ISSUE TITLE
Refactor `output_stresses` function

### ISSUE THREAD

**Issue by kks32** [cbgeo-archives/mpm-point-generator#1]
* Merge `output_3d_stresses` and `output_stresses` function into a single function.

**Comment by ezrayst** [comment]
@kks32, I was reviewing this. Seems that you have not commented on anything since I last pushed. You did fix the issues and the PR

**Comment by kks32** [comment]
The following parameters should be read from an input file.

```
  // Material density
  const double density = 22;
  // K0 static pressure coefficient
  const double k0 = 0.5;
  const double max_height = 3;
  const double conv_factor = 10;
```

**Comment by kks32** [comment]
Use dynamic vectors from Eigen3 `VectorXd` to store stresses. Depends on #19

**Comment by ezrayst** [comment]
I guess we can merge this to #32

**Comment by kks32** [comment]
#36 fixes
