### ISSUE TITLE
Use Eigen for vectors

### ISSUE THREAD

**Issue by kks32** [cbgeo-archives/mpm-point-generator#19]
* Use Eigen library for coordinates and stresses

**Comment by ezrayst** [comment]
@kks32, this issue is not done yet? I thought we have used Eigen for coordinate? Again, I see your last commit but I haven't seen any comments from previous commits

**Comment by kks32** [comment]
@ezrayst Point / Mesh class doesn't seem to have coordinates / stresses using Eigen vectors. The issue is not complete, yet.

**Comment by kks32** [comment]
There are no PRs, so no comments.

**Comment by ezrayst** [comment]
I have one more issue about the size of the stress vector (Voigt).
For 3D, it is surely of size 6. But for 2D, I recalled that we keep using 6 as well right? if not then it is 3. But how do we get a general statement that depends on `Tdim` for both 3D and 2D? 

Currently, even in `develop` branch, we have `Tdim * 2` which is not really correct I think
