### ISSUE TITLE
Refactor compute_stress function

### ISSUE THREAD

**Issue by ezrayst** [cbgeo-archives/mpm-point-generator#32]
- currently not implemented for 2D
- need to make a new input file that has parameters required for stress computation
- `max_height` should be computed instead of inputed
- size of the stress vector need to be determined. I think `Tdim * 2` is currently wrong for 2D
- should not be in `gmsh.tcc` (not sure where to put them)

**Comment by ezrayst** [comment]
Where should I have the compute_stress functions? and the input files would be `mesh file` and `material input` to include the density, K0 etc?

**Comment by kks32** [comment]
Could we have a class `Points`, which has a list of points and the associated material?

**Comment by ezrayst** [comment]
This will be separated from our `point.h`?

**Comment by kks32** [comment]
Yes, a class that has a collection of points. This will be useful for multiple material models

**Comment by ezrayst** [comment]
I will be writing as follow:

(1) `materialpoints_` from `mesh.h` would be changed to a new class points (instead of shared_ptr to point)
(2) `points.h` would include data: `point`, along with `density` and `k0` to calculate the stress
(3) `compute_stress()` will be moved from `gmsh` to `points`

Would this work?

**Comment by kks32** [comment]
`Points` should have a pointer to a material model class, which can hold information on density and k0.

**Comment by ezrayst** [comment]
so we want to make another class: `material` then? this includes `density` and `k0`.

so `points.h` would have a pointer to both `point` and `material` then? And here is where the `compute_stress()` would be done?

**Comment by ezrayst** [comment]
Would `Points` have vector of `Point` or just pointer to one??

**Comment by kks32** [comment]
`Points` will have a vector of pointers to `Point` objectss

**Comment by ezrayst** [comment]
Design would be such as:
- `Points` would have pointers to `Point` (id, coord, stress) and `MaterialProperties` (density, k0)
- 'Mesh' and subsequent child class, would have vector of pointers to `Points` instead of `Point`
- `compute_stress` would then be calculated not in `Mesh` but in `Points`

**Comment by kks32** [comment]
#36 fixes
