### ISSUE TITLE
output initial stress and volume id should be from global_id of points

### ISSUE THREAD

**Issue by ezrayst** [cbgeo-archives/mpm-point-generator#58]

**Comment by ezrayst** [comment]
I was thinking rather than using `id = 0` and `++id`, we can output the `global-id` of each point but it will be quite expensive (looping a vector, and have to refactor our range-based loop). What do you think? @kks32 and @cw646

**Comment by kks32** [comment]
You could potentially return an iterator for material points container and iterate over that.
