### ISSUE TITLE
Assigning mesh to different material properties

### ISSUE THREAD

**Issue by ezrayst** [cbgeo-archives/mpm-point-generator#63]
Current implementation is able to handle more than one material for a gmsh file, but does not assign which part for which material.

Proposed work:
- Have two mesh files?
- Or within the mesh set which mesh has which material properties?

Any suggestion?

**Comment by kks32** [comment]
Set groups within a single mesh to handle regions of no material points, and material points with different material properties.

**Comment by ezrayst** [comment]
I can think of a few ways, but not sure which one should we go with:
- By coordinate: so if it is within these boundaries then assign to material 1, then if not material 2
- By another mesh that defines a boundary?

I like the first one better. But how about an arbitrary shape?

In 2D it would be simple, noting that the geology is like a layered-cake. But in 3D case where geology is complicated, it would be quite intensive I think.

**Comment by kks32** [comment]
GMSH allows you to group, can we not use grouping to define different regions in a mesh?
