### ISSUE TITLE
Initial stress is not computed properly

### ISSUE THREAD

**Issue by ezrayst** [cbgeo-archives/mpm-point-generator#64]
The current implementation finds the maximum height (highest vertical coordinate). It will not work with sloping or even non-flat surface. 

Proposed work:
- Maybe we can turn on gravity loading type of method to make sure we get correct initial stresses

**Comment by kks32** [comment]
This is a point generator, you don't have the physics to turn-on gravity. This cannot be fixed in the point generator code.
