### ISSUE TITLE
Make material points from Tetrahedron

### ISSUE THREAD

**Issue by ezrayst** [cbgeo-archives/mpm-point-generator#65]
I expect most of the 3D landslide model would have to be meshed using delaunay type of algorithm (triangles). I will start by implementing tetrahedron since I need it for HK project.

Note that we still use quadrilateral and hexahedron background mesh.

**Comment by kks32** [comment]
Could you please elaborate on why this should be the case?

**Comment by ezrayst** [comment]
Automatic meshing (using gmsh) is not available for quarilateral-family elements. We can get away with it by using layers but it will not work for non prismatic body. Slump cone is still OK, but arbitrary topography would not work. 

Since the aim is to only get material points, we can reduce work by using automatic mesh in tetrahedron, then get the material points on the centroid of each element with the element volume and mass associated with them. 

This has nothing to do with the calculations since we will still use quadrilateral-type background mesh.

**Comment by cw646** [comment]
I'll take a look at GMSH hex mesh generation of a more arbitrary shape, IIRC - I think it could be done, but certainly not intuitively.

**Comment by ezrayst** [comment]
Thanks @cw646, I personally think what you did before was layering and your slump cone was rather "structured" mesh. In case of a landslide, it is very unstructured
